// <auto-generated />
using System;
using ControleEstoque.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleEstoque.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleEstoque.Models.Estoque", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("estoques");
                });

            modelBuilder.Entity("ControleEstoque.Models.ItemVenda", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id"));

                    b.Property<int?>("idEstoque")
                        .HasColumnType("integer");

                    b.Property<int?>("idProduto")
                        .HasColumnType("integer");

                    b.Property<int?>("idVenda")
                        .HasColumnType("integer");

                    b.Property<float?>("precoProduto")
                        .HasColumnType("real");

                    b.Property<float>("valorDesconto")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("itemVenda");
                });

            modelBuilder.Entity("ControleEstoque.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("id"));

                    b.Property<DateTime?>("dataMovimentacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("idEstoque")
                        .HasColumnType("integer");

                    b.Property<int?>("idItemVenda")
                        .HasColumnType("integer");

                    b.Property<int?>("idProduto")
                        .HasColumnType("integer");

                    b.Property<float?>("quantidade")
                        .HasColumnType("real");

                    b.Property<string>("tipoMovimentacao")
                        .HasColumnType("text");

                    b.Property<float?>("valorMovimentacao")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("movimentacaoEstoque");
                });

            modelBuilder.Entity("ControleEstoque.Models.Produto", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("descricao")
                        .HasColumnType("text");

                    b.Property<float?>("preco")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("produto");
                });

            modelBuilder.Entity("ControleEstoque.Models.Venda", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("dataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("quantidadeTotal")
                        .HasColumnType("integer");

                    b.Property<float>("valorDescontoTotal")
                        .HasColumnType("real");

                    b.Property<float?>("valorVenda")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("venda");
                });
#pragma warning restore 612, 618
        }
    }
}
